name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.OVH_VPS_SSH_HOST }}
          username: ${{ secrets.OVH_VPS_SSH_USER }}
          key: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          source: target/*.jar
          target: /home/${{ secrets.SSH_USERNAME }}/app.jar

      - name: Deploy Spring Boot App
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.OVH_VPS_SSH_HOST }}
          username: ${{ secrets.OVH_VPS_SSH_USER }}
          key: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop notes
            sudo mv /home/${{ secrets.OVH_VPS_SSH_USER }}/app.jar /opt/notes/app.jar
            sudo systemctl start notes
