name: Deploy Spring Boot Application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update notes.service with secrets and restart the service
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.OVH_VPS_SSH_HOST }}
          username: ${{ secrets.OVH_VPS_SSH_USER }}
          key: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OVH_VPS_SSH_PORT }}
          script: |
            sudo sed -i '/^Environment=/d' /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_DB_POSTGRESQL_URL=${{ secrets.OVH_VPS_DB_POSTGRESQL_URL }}\"" | sudo tee -a /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_DB_POSTGRESQL_USERNAME=${{ secrets.OVH_VPS_DB_POSTGRESQL_USERNAME }}\"" | sudo tee -a /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_DB_POSTGRESQL_PASSWORD=${{ secrets.OVH_VPS_DB_POSTGRESQL_PASSWORD }}\"" | sudo tee -a /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_MAIL_SERVER_SMTP_PORT=${{ secrets.OVH_VPS_MAIL_SERVER_SMTP_PORT }}\"" | sudo tee -a /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_MAIL_SERVER_SMTP_USERNAME=${{ secrets.OVH_VPS_MAIL_SERVER_SMTP_USERNAME }}\"" | sudo tee -a /etc/systemd/system/notes.service
            echo "Environment=\"OVH_VPS_MAIL_SERVER_SMTP_PASSWORD=${{ secrets.OVH_VPS_MAIL_SERVER_SMTP_PASSWORD }}\"" | sudo tee -a /etc/systemd/system/notes.service

            sudo systemctl daemon-reload
            sudo systemctl restart notes.service

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.OVH_VPS_SSH_HOST }}
          username: ${{ secrets.OVH_VPS_SSH_USER }}
          key: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OVH_VPS_SSH_PORT }}
          source: target/notes_v2-0.0.1-SNAPSHOT.jar
          target: /opt/notes

      - name: Deploy Spring Boot App
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.OVH_VPS_SSH_HOST }}
          username: ${{ secrets.OVH_VPS_SSH_USER }}
          key: ${{ secrets.OVH_VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.OVH_VPS_SSH_PORT }}
          
            sudo systemctl stop notes.service
            sudo systemctl start notes.service